---
title: "Increasing association between child poverty and out-of-home care - longitudinal ecological analysis of Finnish municipalities in 1992-2020"
format: html
editor: visual
code-fold: true
always_allow_html: true
---
```{r}
#| echo: false
#| output: false
library(magrittr) #
library(tidyverse) #
#library(hrbrthemes)
#library(viridis)
library(datawizard)
#library(haven)
library(ggplot2)
#library(lmtest)
#library(Rcpp)
library(geomtextpath)
library(sotkanet)
library(Hmisc)
library(dplyr)
library(janitor)
#library(naniar)
library(sandwich)
library(lmtest)
library(modelsummary)
library(estimatr)
library(lme4)
library(sjlabelled)
#library(VIM)
library("modelr")
library(robustlmm)
library(gganimate)
#library(gifski)
library(readr)
library(tidyr)
library(transformr)
library(robustlmm)
library("readxl")
library(ggpubr)

#clearing memory
rm(list=ls())


```


## Regression models

```{r}
#| warning: false 
#| tbl-cap: "Association between child poverty and out-of-home care in Finnish municipalities. Linear models. The Frist three models are without municipality fixed effects. "
setwd("C:/Users/AapoHiilamo/OneDrive - Itsenäisyyden juhlavuoden lastensäätiö sr/Tiedostot/Lastensuojelu ja köyhyys/research_paper_ohc")

rm(list=ls())
load("./data/processed/data_imputed.RData")
load("./data/processed/data_imputed_teens.RData")

model.data <- filter(dsw.d, region.class == "KUNTA" & gender == "total")

#write.dta(model.data, "C:/Users/HIILAMO/Downloads/mydata.dta")

all.years <- filter(dsw.d, region.class == "KUNTA" & gender == "total")
Years.1992.01 <- filter(all.years, year %in% (1992:2001))
Years.2002.11 <- filter(all.years, year %in% (2002:2011))
Years.2012.21 <- filter(all.years, year %in% (2012:2021))

datasets <- list(all.years, 
          Years.1992.01,
          Years.2002.11,
          Years.2012.21)

lmrobust <- function(dataset) {
  lm_robust(ohc ~ poverty + unemp + factor(year), clusters = region, data = dataset)
}

within_between <- function(data) {
  dsw.d.wb <- cbind(data,
  datawizard::demean(data, select = c("poverty",  "unemp"),
                     group = "region"))
 lmer(ohc ~ poverty_within +  
         poverty_between + 
         unemp_within+
         unemp_between +
         factor(year)+ 
         (1 | region),  
       data =  dsw.d.wb )
}

within_between <- function(dataset) {
  lm_robust(ohc ~ poverty + unemp + factor(year), clusters = region, data = dataset, fixed_effects = ~ region)

}

results1 <- purrr::map(datasets,lmrobust)
results2 <- purrr::map(datasets,within_between)

results <-c(results1,results2)
modelsummary(
  results, gof_map = c("nobs", "r.squared"),
  fmt = 2,
  estimate  = "{estimate} [{conf.low}, {conf.high}]",
  statistic = NULL,
  coef_omit = "factor*|Intercept|region*|unemp*", 
  notes = "Models include years as factor and unemployment rate")






```

## Regression models - female

```{r}
#| warning: false 
#| tbl-cap: "Association between child poverty and out-of-home care in Finnish municipalities. Linear models."

model.data <- filter(dsw.d, region.class == "KUNTA" & gender == "female")

#write.dta(model.data, "C:/Users/HIILAMO/Downloads/mydata.dta")

all.years <- filter(dsw.d, region.class == "KUNTA" & gender == "female")
Years.1992.01 <- filter(all.years, year %in% (1992:2001))
Years.2002.11 <- filter(all.years, year %in% (2002:2011))
Years.2012.21 <- filter(all.years, year %in% (2012:2021))
datasets <- list(all.years, 
          Years.1992.01,
          Years.2002.11,
          Years.2012.21)



results1 <- purrr::map(datasets,lmrobust)
results2 <- purrr::map(datasets,within_between)

results <-c(results1,results2)
modelsummary(
  results, gof_map = c("nobs", "r.squared"),
  fmt = 2,
  estimate  = "{estimate} [{conf.low}, {conf.high}]",
  statistic = NULL,
  coef_omit = "factor*|Intercept|region*|unemp*", 
  notes = "Models include years as factor and unemployment rate")





```

## Regression models - male

```{r}
#| warning: false 
#| tbl-cap: "Association between child poverty and out-of-home care in Finnish municipalities. Linear models."

#| warning: false 
#| tbl-cap: "Association between child poverty and out-of-home care in Finnish municipalities. Linear models."

model.data <- filter(dsw.d, region.class == "KUNTA" & gender == "male")

#write.dta(model.data, "C:/Users/HIILAMO/Downloads/mydata.dta")

all.years <- filter(dsw.d, region.class == "KUNTA" & gender == "male")
Years.1992.01 <- filter(all.years, year %in% (1992:2001))
Years.2002.11 <- filter(all.years, year %in% (2002:2011))
Years.2012.21 <- filter(all.years, year %in% (2012:2021))
datasets <- list(all.years, 
          Years.1992.01,
          Years.2002.11,
          Years.2012.21)



results1 <- purrr::map(datasets,lmrobust)
results2 <- purrr::map(datasets,within_between)

results <-c(results1,results2)
modelsummary(
  results, gof_map = c("nobs", "r.squared"),
  fmt = 2,
  estimate  = "{estimate} [{conf.low}, {conf.high}]",
  statistic = NULL,
  coef_omit = "factor*|Intercept|region*|unemp*", 
  notes = "Models include years as factor and unemployment rate")



```

## Regression models - preteenagers

```{r}
#| warning: false 
#| tbl-cap: "Association between child poverty and out-of-home care in Finnish municipalities. Linear models."
teens_kunta <- filter(teens, region.class == "KUNTA")

all.years <- filter(teens_kunta, region.class == "KUNTA" & gender == "total" & age.group == "Ages 0 - 12")
all.years$ohc<- all.years$ohc_age
#write.dta(model.data, "C:/Users/HIILAMO/Downloads/mydata.dta")

Years.1992.01 <- filter(all.years, year %in% (1992:2001))
Years.2002.11 <- filter(all.years, year %in% (2002:2011))
Years.2012.21 <- filter(all.years, year %in% (2012:2021))
datasets <- list(all.years, 
          Years.1992.01,
          Years.2002.11,
          Years.2012.21)


results1 <- purrr::map(datasets,lmrobust)
results2 <- purrr::map(datasets,within_between)

results <-c(results1,results2)
modelsummary(
  results, gof_map = c("nobs", "r.squared"),
  fmt = 2,
  estimate  = "{estimate} [{conf.low}, {conf.high}]",
  statistic = NULL,
  coef_omit = "factor*|Intercept|region*|unemp*", 
  notes = "Models include years as factor and unemployment rate")





```

## Regression models - teenagers

```{r}
#| warning: false 
#| tbl-cap: "Association between child poverty and out-of-home care in Finnish municipalities. Linear models."
all.years <- filter(teens_kunta, region.class == "KUNTA" & gender == "total" & age.group == "Ages 13 - 17")
all.years$ohc<- all.years$ohc_age

#write.dta(model.data, "C:/Users/HIILAMO/Downloads/mydata.dta")

Years.1992.01 <- filter(all.years, year %in% (1992:2001))
Years.2002.11 <- filter(all.years, year %in% (2002:2011))
Years.2012.21 <- filter(all.years, year %in% (2012:2021))
datasets <- list(all.years, 
          Years.1992.01,
          Years.2002.11,
          Years.2012.21)


results1 <- purrr::map(datasets,lmrobust)
results2 <- purrr::map(datasets,within_between)

results <-c(results1,results2)
modelsummary(
  results, gof_map = c("nobs", "r.squared"),
  fmt = 2,
  estimate  = "{estimate} [{conf.low}, {conf.high}]",
  statistic = NULL,
  coef_omit = "factor*|Intercept|region*|unemp*", 
  notes = "Models include years as factor and unemployment rate")

```


## Regression models - larger geographical units

```{r}
#| label: gif_MAAKUNTA
#| fig-cap: Child poverty rate (5 of families with social assistance) in Finnish municipalities between 1992 and 2020.
#| warning: false 
#| eval: true


all.years <- filter(dsw.d, region.class == "MAAKUNTA" & gender == "total")
Years.1992.01 <- filter(all.years, year %in% (1992:2001))
Years.2002.11 <- filter(all.years, year %in% (2002:2011))
Years.2012.21 <- filter(all.years, year %in% (2012:2021))
datasets <- list(all.years, 
          Years.1992.01,
          Years.2002.11,
          Years.2012.21)


results1 <- purrr::map(datasets,lmrobust)
results2 <- purrr::map(datasets,within_between)

results <-c(results1,results2)
modelsummary(
  results, gof_map = c("nobs", "r.squared"),
  fmt = 2,
  estimate  = "{estimate} [{conf.low}, {conf.high}]",
  statistic = NULL,
  coef_omit = "factor*|Intercept|region*|unemp*", 
  notes = "Models include years as factor and unemployment rate")




```
